version: "3.7"
services:
  nginx-sandbox:
    container_name: nginx-sandbox
    build:
      context: .docker/nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app-php
    networks:
      - default

# sandbox php folder
  app-php:
    container_name: app-php
    build:
      context: .docker/php-fpm
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes:
      - .:/var/www
      - .docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    links:
      - db-sandbox
    ports:
    - 9000:9000
    networks:
      - default

  db-sandbox:
    container_name: db-sandbox
    image: mysql:latest
    env_file: .docker/db/.env
    ports:
      - 33306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  phpmyadmin-sandbox:
    container_name: phpmyadmin-sandbox
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db-sandbox
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "9998:80"
    links:
      - db-sandbox
    networks:
      - default

volumes:
  mysql-data:

networks:
  default:
    driver: bridge