version: "3.7"
services:
  nginx-sandbox:
    container_name: nginx-sandbox
    build:
      context: .docker/nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app-php
    networks:
      - default

# sandbox php folder
  app-php:
    container_name: app-php
    build:
      context: .docker/php-fpm
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes:
      - .:/var/www
      - .docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    links:
      - db-sandbox
    ports:
    - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  db-sandbox:
    container_name: db-sandbox
    image: postgres:12
    env_file: .docker/db/.env
    ports:
      - 54321:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin-sandbox:
    container_name: pgadmin-sandbox
    image: dpage/pgadmin4:4.27
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@toto.com
      PGADMIN_DEFAULT_PASSWORD: toto
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9998:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db-sandbox:pgsql-server"
    networks:
      - default

volumes:
  db-data:
  pgadmin-data:

networks:
  default:
    driver: bridge